In [10]:
#Machine Learning For Data Science
#1.Import Important Libraries

import pandas as pd
import numpy as np

from sklearn.neighbors import KNeighborsClassifier    #algorithms KNN
from sklearn.model_selection import train_test_split  #Data training or testing split
from sklearn.metrics import accuracy_score            #Model performance

In [11]:
#2.Import Dataset
import kagglehub

# Download latest version
path = kagglehub.dataset_download("jayantiprasad/student-exam-results-dataset")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\bhupe\.cache\kagglehub\datasets\jayantiprasad\student-exam-results-dataset\versions\1

In [12]:
df =pd.read_csv(f'{path}/results.csv')
df.head()

,Unnamed: 0,Hindi,English,Science,Maths,History,Geograpgy,Total,Results,Div
0,0,65,10,59,3,71,37,245,0,3
1,1,94,56,4,67,91,50,362,1,1
2,2,7,85,76,99,60,25,352,0,2
3,3,88,46,59,94,52,38,377,1,1
4,4,39,81,37,38,6,54,255,1,3

In [13]:
#3.Data Cleaning/PreProcessing
df.columns

Index(['Unnamed: 0', 'Hindi', 'English', 'Science', 'Maths', 'History',
       'Geograpgy', 'Total', 'Results', 'Div'],
      dtype='object')

In [14]:
df=df.drop(columns=['Unnamed: 0','Div'])

In [15]:
df.head(2)

   Hindi  English  Science  Maths  History  Geograpgy  Total  Results
0     65       10       59      3       71         37    245        0
1     94       56        4     67       91         50    362        1

In [16]:
df.isnull().sum()

Hindi        0
English      0
Science      0
Maths        0
History      0
Geograpgy    0
Total        0
Results      0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
#4.Split column in input/output

df.head()

   Hindi  English  Science  Maths  History  Geograpgy  Total  Results
0     65       10       59      3       71         37    245        0
1     94       56        4     67       91         50    362        1
2      7       85       76     99       60         25    352        0
3     88       46       59     94       52         38    377        1
4     39       81       37     38        6         54    255        1

In [19]:
df.columns

Index(['Hindi', 'English', 'Science', 'Maths', 'History', 'Geograpgy', 'Total',
       'Results'],
      dtype='object')

In [20]:
X= df[['Hindi', 'English', 'Science', 'Maths', 'History', 'Geograpgy', 'Total']]
Y= df['Results']

In [21]:
#5.Split data into training and testing

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [22]:
X_train

     Hindi  English  Science  Maths  History  Geograpgy  Total
29      93       41       42     98       72         84    430
535      2       50       96     64       45         76    333
695     71       16       69     60       28         26    270
557     85       88       39     97       31         15    355
836     62       12       25     58       82         59    298
..     ...      ...      ...    ...      ...        ...    ...
106     15        4       18     23       58         20    138
270     37       63       55     62       55         66    338
860     84       36       55     14       22         61    272
435     77       76       22     35        1         14    225
102     96       13       99     46       23         84    361

[800 rows x 7 columns]

In [23]:
#6.Create the model

model=KNeighborsClassifier(
    n_neighbors=5
)

In [24]:
#7.Train the model
model.fit(X_train,Y_train)

KNeighborsClassifier()

In [25]:
#8.Prediction

predict= model.predict(X_test)
predict

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0])

In [27]:
com= pd.DataFrame({'Actual':Y_test,'Prediction':predict})
com

     Actual  Prediction
521       0           0
737       1           1
740       0           0
660       1           0
411       0           0
..      ...         ...
408       1           1
332       1           1
208       0           0
613       0           0
78        0           0

[200 rows x 2 columns]

In [28]:
#9.Evaluation and Accuracy
score= accuracy_score(Y_test,predict)
print('The Accuracy is',score*100)

The Accuracy is 89.0

In [30]:
#10.Deployment
import pickle

pickle.dump(model,open('model.pkl','wb'))
print("PKL File Created")

PKL File Created